// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using elasticsearch_netcore.Models;

#nullable disable

namespace ElasticsearchArticlesApiNetcore.Migrations
{
    [DbContext(typeof(ElasticsearchDBContext))]
    [Migration("20260521021840_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("elasticsearch_netcore.Models.Article", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Abstract")
                        .HasColumnType("text")
                        .HasColumnName("abstract");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime?>("PublishedOn")
                        .HasColumnType("date")
                        .HasColumnName("published_on");

                    b.Property<long?>("Shares")
                        .HasColumnType("integer")
                        .HasColumnName("shares");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Url")
                        .HasColumnType("varchar")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("index_articles_on_created_at");

                    b.HasIndex("Title")
                        .HasDatabaseName("index_articles_on_title");

                    b.HasIndex(new[] { "CreatedAt" }, "index_articles_on_created_at");

                    b.HasIndex(new[] { "Title" }, "index_articles_on_title");

                    b.ToTable("articles");
                });

            modelBuilder.Entity("elasticsearch_netcore.Models.ArticlesCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<long>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("article_id");

                    b.Property<long>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("index_articles_categories_on_article_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("index_articles_categories_on_category_id");

                    b.HasIndex(new[] { "ArticleId" }, "index_articles_categories_on_article_id");

                    b.HasIndex(new[] { "CategoryId" }, "index_articles_categories_on_category_id");

                    b.ToTable("articles_categories");
                });

            modelBuilder.Entity("elasticsearch_netcore.Models.Author", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("index_authors_on_first_name_last_name");

                    b.HasIndex(new[] { "FirstName", "LastName" }, "index_authors_on_first_name_last_name");

                    b.ToTable("authors");
                });

            modelBuilder.Entity("elasticsearch_netcore.Models.Authorship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<long>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("article_id");

                    b.Property<long>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("index_authorships_on_article_id");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("index_authorships_on_author_id");

                    b.HasIndex(new[] { "ArticleId" }, "index_authorships_on_article_id");

                    b.HasIndex(new[] { "AuthorId" }, "index_authorships_on_author_id");

                    b.ToTable("authorships");
                });

            modelBuilder.Entity("elasticsearch_netcore.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .HasDatabaseName("index_categories_on_title");

                    b.HasIndex(new[] { "Title" }, "index_categories_on_title");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("elasticsearch_netcore.Models.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<long>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("article_id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool?>("Pick")
                        .HasColumnType("boolean")
                        .HasColumnName("pick");

                    b.Property<long?>("Stars")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("user");

                    b.Property<string>("UserLocation")
                        .HasColumnType("varchar")
                        .HasColumnName("user_location");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("index_comments_on_article_id");

                    b.HasIndex(new[] { "ArticleId" }, "index_comments_on_article_id");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("elasticsearch_netcore.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("elasticsearch_netcore.Models.ArticlesCategory", b =>
                {
                    b.HasOne("elasticsearch_netcore.Models.Article", "Article")
                        .WithMany("ArticlesCategories")
                        .HasForeignKey("ArticleId")
                        .IsRequired();

                    b.HasOne("elasticsearch_netcore.Models.Category", "Category")
                        .WithMany("ArticlesCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("elasticsearch_netcore.Models.Authorship", b =>
                {
                    b.HasOne("elasticsearch_netcore.Models.Article", "Article")
                        .WithMany("Authorships")
                        .HasForeignKey("ArticleId")
                        .IsRequired();

                    b.HasOne("elasticsearch_netcore.Models.Author", "Author")
                        .WithMany("Authorships")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("elasticsearch_netcore.Models.Comment", b =>
                {
                    b.HasOne("elasticsearch_netcore.Models.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("elasticsearch_netcore.Models.Article", b =>
                {
                    b.Navigation("ArticlesCategories");

                    b.Navigation("Authorships");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("elasticsearch_netcore.Models.Author", b =>
                {
                    b.Navigation("Authorships");
                });

            modelBuilder.Entity("elasticsearch_netcore.Models.Category", b =>
                {
                    b.Navigation("ArticlesCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
